name: flutter_almightyflippa
description: "LABBY"
publish_to: "none"

version: 1.0.10+10 # Android
# version: 1.0.0+1 # Android TV
# version: 1.0.0+1 # IOS

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI
  get: ^4.7.3
  flutx_core: ^1.1.1+1
  shimmer: ^3.0.0
  file_picker: ^10.3.8
  pin_code_fields: ^9.1.0
  image_picker: ^1.2.1

  # Network and cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  equatable: ^2.0.8
  dartz: ^0.10.1
  flutter_secure_storage: ^10.0.0
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  
  # Video
  video_player: ^2.11.1
  chewie: ^1.13.0
  media_kit: ^1.1.10
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.4
  floating: ^6.0.0

  # Icons for app
  flutter_launcher_icons: ^0.14.4
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash_and_login_logo.png"
  # adaptive_icon_background: "#db1f12"
  # adaptive_icon_foreground: "assets/images/splash_and_login_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/splash_and_login_logo.png"
    background_color: "#111111"
    theme_color: "#111111"
  windows:
    generate: true
    image_path: "assets/images/splash_and_login_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/splash_and_login_logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    
