// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDjH06mG6i9kkUcaVbkbqMJm3rrNWbKY',
    appId: '1:388967030869:web:72ada624b6e6fc5d0d74dc',
    messagingSenderId: '388967030869',
    projectId: 'labby-tv623',
    authDomain: 'labby-tv623.firebaseapp.com',
    storageBucket: 'labby-tv623.firebasestorage.app',
    measurementId: 'G-7VXW4K362D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfRrMmfX2qY59hT6LwQ8sVdzeuyFg81cQ',
    appId: '1:388967030869:android:c316c5649cbac1bc0d74dc',
    messagingSenderId: '388967030869',
    projectId: 'labby-tv623',
    storageBucket: 'labby-tv623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmkNuZzKKOnI47pCOi2zXj4sNucMN3kjI',
    appId: '1:388967030869:ios:f3d63166dba6619d0d74dc',
    messagingSenderId: '388967030869',
    projectId: 'labby-tv623',
    storageBucket: 'labby-tv623.firebasestorage.app',
    iosBundleId: 'com.almightyflippa.labbytv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmkNuZzKKOnI47pCOi2zXj4sNucMN3kjI',
    appId: '1:388967030869:ios:a4fe653c9fa727f20d74dc',
    messagingSenderId: '388967030869',
    projectId: 'labby-tv623',
    storageBucket: 'labby-tv623.firebasestorage.app',
    iosBundleId: 'com.example.flutterAlmightyflippa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJDjH06mG6i9kkUcaVbkbqMJm3rrNWbKY',
    appId: '1:388967030869:web:8ad29d59907c24500d74dc',
    messagingSenderId: '388967030869',
    projectId: 'labby-tv623',
    authDomain: 'labby-tv623.firebaseapp.com',
    storageBucket: 'labby-tv623.firebasestorage.app',
    measurementId: 'G-ZDW5YWX6D4',
  );
}
